name: Playwright Tests
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'
env:
  # Warnings breaks build on CI
  # See: https://github.com/orgs/community/discussions/25228#discussioncomment-3246960
  CI: false
  MODE: standalone
  KETCHER_URL: http://frontend:4002
jobs:
  playwright_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install dependencies
        run: npm ci
      - name: Build all packages
        run: npm run build
      - name: Build frontend for docker
        run: npm run docker:build
      - name: Build playwright tests in docker
        run: docker-compose build autotests
      - name: Run playwright tests in docker
        run: cd ketcher-autotests && npm run docker:test:ci
      - uses: actions/upload-artifact@v3
        # run even if previous steps fails
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
