name: Run Playwright Tests (FullScale)
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'
  workflow_dispatch:

env:
  # Warnings breaks build on CI
  # See: https://github.com/orgs/community/discussions/25228#discussioncomment-3246960
  CI: false
  MODE: standalone
  KETCHER_URL: http://127.0.0.1:4002
  DOCKER: true
  IGNORE_UNSTABLE_TESTS: true
  CI_ENVIRONMENT: true
  USE_SEPARATE_INDIGO_WASM: true
jobs:
  build_ketcher:
    runs-on: ubuntu-latest
    container: node:18.14-bullseye-slim
    steps:
      - name: Install dependencies
        run: apt-get update -y && apt-get install -y git
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Git safe
        run: git config --global --add safe.directory '*'
      - name: Install NPM dependencies
        run: npm ci
      - name: Build all packages
        run: npm run build:packages && npm run build:example:standalone
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ketcher-dist-micro
          path: example/dist

  part:
    timeout-minutes: 120
    runs-on: self-hosted-a
    needs: build_ketcher
    container: mcr.microsoft.com/playwright:v1.44.1-jammy
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6]
        shardTotal: [6]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: npm ci
      - name: Create folder for dist
        run: mkdir -p example/dist
      - name: Download compiled ketcher
        uses: actions/download-artifact@v4
        with:
          name: ketcher-dist-micro
          path: example/dist/
      - name: Create env file
        run: |
          cat > ketcher-autotests/.env << EOF
          DOCKER=true
          KETCHER_URL=$KETCHER_URL
          MODE=$MODE
          IGNORE_UNSTABLE_TESTS=$IGNORE_UNSTABLE_TESTS
          CI_ENVIRONMENT=$CI_ENVIRONMENT
          USE_SEPARATE_INDIGO_WASM=$USE_SEPARATE_INDIGO_WASM
          EOF
      - name: Run tests
        run: |
          cd example/ && nohup npm run serve:standalone &
          cd ketcher-autotests/
          npm i
          npx playwright install chromium
          npx playwright test \
            --project=chromium \
            --grep-invert @chromium-popup \
            --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} \
            --reporter=blob

      - name: Check blob-report directory
        if: always()
        run: |
          pwd
          ls -la blob-report

      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
  merge-reports:
    if: always()
    needs: [part]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: Download blob-report-1
        uses: actions/download-artifact@v4
        with:
          name: blob-report-1
          path: all-blob-reports/blob-report-1

      - name: Download blob-report-2
        uses: actions/download-artifact@v4
        with:
          name: blob-report-2
          path: all-blob-reports/blob-report-2

      - name: Download blob-report-3
        uses: actions/download-artifact@v4
        with:
          name: blob-report-3
          path: all-blob-reports/blob-report-3

      - name: Download blob-report-4
        uses: actions/download-artifact@v4
        with:
          name: blob-report-4
          path: all-blob-reports/blob-report-4

      - name: Download blob-report-5
        uses: actions/download-artifact@v4
        with:
          name: blob-report-5
          path: all-blob-reports/blob-report-5

      - name: Download blob-report-6
        uses: actions/download-artifact@v4
        with:
          name: blob-report-6
          path: all-blob-reports/blob-report-6

      - name: Verify downloaded reports
        run: ls -laR all-blob-reports

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 7
